### ISSUE TITLE
Code is not working 

### ISSUE THREAD

**Issue by zeynepozdemir** [xmed-lab/SCAN#1]
Congratulations on your very good work. That's why I wanted to run models myself. I did the installations. When I try to train afterwards, I keep getting an error. Can you help me.
![Screenshot from 2022-08-03 11-07-26](https://user-images.githubusercontent.com/6259137/182558122-50484937-7c04-48dc-b217-8065abd031fb.png)

**Comment by ustlsh** [comment]
You can check the version of 'faiss'. My version is 1.6.3, which should be fine.
<img width="147" alt="image" src="https://user-images.githubusercontent.com/97079374/184524523-f495cd74-5c8e-49e6-80be-e3bfeadc6616.png">

**Comment by zeynepozdemir** [comment]
Thank you :)
