### ISSUE TITLE
SD-198

### ISSUE THREAD

**Issue by Fu-Zhou-2019** [xmed-lab/SCAN#2]
Nice work! But the SD-198 dataset can't be downloaded, can you provide the google drive link or another way to download it?

**Comment by Xglbrilliant** [comment]
> 干得好！但是SD-198数据集下载不了，能提供一下google drive链接或者其他方式下载吗？


Do you have a download link available? Greatful!

**Comment by MeycL** [comment]
Do Authors have a download link available?
